version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=posgree_tfg_user
      - POSTGRES_PASSWORD=GANCVzIwMK5d4i5F8MWOMoBprbmNHqpY
      - POSTGRES_DB=posgree_tfg

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bartu@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bartu"
    ports:
      - "80:80"
    depends_on:
      - postgres
