version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgretfg_user
      - POSTGRES_PASSWORD=nVAqjkOJ00gXd799hilNSHcVmhRJXQap
      - POSTGRES_DB=postgretfg

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bartu@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bartu"
    ports:
      - "80:80"
    depends_on:
      - postgres
